### ISSUE TITLE
Opens only in a small part of the screen

### ISSUE THREAD

**Issue by bhavikbhavsar** [LekoArts/gatsby-starter-portfolio-jodie#11] opened 2019-03-15 09:57 UTC
![image](https://user-images.githubusercontent.com/4545441/54423459-bb700e80-4736-11e9-9e19-c53ff65757bc.png)

**Comment by LekoArts** [comment] 2019-03-20 16:14
Can't reproduce that. Do you have more information at hand?

**Comment by LekoArts** [comment] 2019-03-25 16:11
Closing this issue then. If you still see that problem: Please provide more information on how to re-create that issue.

**Closed by LekoArts** 2019-03-25 16:11 UTC
